 const menuList = [
    {
        title:'首页',
        key:'/admin/home'
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'按钮',
                key:'/admin/ui/buttons'
            },
            {
                title:'弹框',
                key:'/admin/ui/modals'
            },
        ]

    },
    {
        title:'表单',
        key:'/admin/form'
    },
    {
        title:'表格',
        key:'/admin/table'
    },
    {
        title:'富文本',
        key:'/admin/text'
    },
    {
        title:'城市管理',
        key:'/admin/city'
    },
    {
        title:'订单管理',
        key:'/admin/order'
    },
    {
        title:'员工管理',
        key:'/admin/person'
    },
    {
        title:'权限设置',
        key:'/admin/setting'
    },
]

export default menuList